/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118242-gf80af3657f-20250105"
#endif /* AVUTIL_FFVERSION_H */
